import React from "react";
import { StyleSheet } from "react-native";


    const styles = StyleSheet.create({
        container:{
            flex:1,
            marginStart:25,
            marginEnd:25,
            flexDirection:'column',
            justifyContent:'flex-start',
            top:24,
        },
        menu:{
            flexDirection:'row',
            justifyContent:'space-between',
            height:24
        },
        menu_con:{
            flexDirection:'row',
        },
        menu_icon:{
            width:24,
            height:24
        },
        account:{
            marginTop:16,
            flexDirection:'row',
            justifyContent:'space-between',
            height:50,
            alignItems:'center'
        },
        account_left:{
            height:50,
            flexDirection:'row',
            justifyContent:'center',
            alignItems:'center'
        },
        logo:{
            width:50,
            height:50
        },
        account_left_tt:{
            flexDirection:'column',
            marginTop:2.5,
            marginLeft:4,
            alignItems:'flex-start',
            width:82,
            height:45
        },
        account_left_tt_name:{
            fontFamily:'Poppins',
            fontWeight:'600',
            fontSize:16,
            lineHeight:24,
            color:'#000000',
        },
        account_left_tt_time:{
            fontFamily:'Poppins',
            fontWeight:'400',
            fontSize:13,
            lineHeight:21,
            color:'#4E4B66',
        },
        button_follo:{
            width:102,
            height:34,
            marginTop:6,
            left:0,
            borderRadius:6,
            backgroundColor:'#1877F2',
            alignItems:'center',
            justifyContent:'center'
        },
        buttonText:{
            fontFamily:'Poppins',
            fontWeight:'600',
            fontSize:16,
            lineHeight:24,
            color:'#FFFFFF',
        },
        image:{
            width:380,
            height:248,
            marginTop:16
        },
        title:{
            marginTop:16,
            height:133
        },
        title_europe:{
            fontFamily:'Poppins',
            fontWeight:'400',
            fontSize:14,
            lineHeight:21,
            color:'#4E4B66',
        },
        title_content:{
            fontFamily:'Poppins',
            fontWeight:'400',
            fontSize:24,
            lineHeight:36,
            color:'#000000',
        },
        noidung:{
            marginTop:16
        },
        noidung_text:{
            fontFamily:'Poppins',
            fontWeight:'400',
            fontSize:16,
            lineHeight:24,
            color:'#4E4B66',
        },
        tuongtac:{
            flexDirection:'row',
            justifyContent:'space-between',
            height:78,
            backgroundColor:'#FFFFFF'
        },
        tuongtac_left:{
            flexDirection:'row',
            width:156,
            height:70,
            marginTop:4
        },
        tuongtac_left_tym:{
            width:70,
            borderRadius:6,
            paddingHorizontal:4,
            paddingVertical:8,
            flexDirection:'row',
            
            
        },
        tuongtac_left_tym_icon:{
            width:24,
            height:24,
            marginLeft:-0.5
        },
        tuongtac_left_tym_text:{
            fontFamily:'Poppins',
            fontWeight:'400',
            fontSize:16,
            lineHeight:24,
            color:'#050505',
        },
        tuongtac_right:{
            width:70,
            height:70,
            marginTop:4,
            borderRadius:6,
            paddingHorizontal:4,
            paddingVertical:8,
            flexDirection:'column',
            
            
        },
        tuongtac_left_cmt_icon:{
            width:24,
            height:24
        }

    })
    export default styles